version: 2

sources:
  - name: raw_data
    description: "Raw data for NYC taxi rides"
    database: kestra-demo-486219
    schema: zoomcamp
    tables:
      - name: green_tripdata
      - name: yellow_tripdata